name: emp_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  pinput: ^5.0.0
  http: ^1.2.1
  dropdown_button2: ^2.3.9
  flutter_secure_storage: ^9.2.2
  device_preview: ^1.2.0
  firebase_messaging: ^15.0.2
  firebase_core: ^3.1.1
  flutter_local_notifications: ^17.2.1
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  persistent_bottom_nav_bar: ^6.2.1
  dio: ^5.5.0+1
  flutter_easyloading: ^3.0.5
  device_info_plus: ^10.1.0
  device_marketing_names: ^0.8.5
  shared_preferences: ^2.2.3
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/image/
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
